context:
  version: "0.9.6"

package:
  name: libcap-ng
  version: ${{ version }}

source:
  url: https://github.com/stevegrubb/libcap-ng/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 399040138e0ca62fa2bcabd63da9af4431a246ef7a654561a0ca3cb00010a539

build:
  number: 0
  script:
    - ./autogen.sh
    # NOTE: we `--disable-cap-audit` since it requires `bpftool`, `libaudit` and `libbpf` which aren't yet packaged for conda-forge
    - ./configure --prefix="$PREFIX" --disable-static --disable-cap-audit --without-python3
    - make -j${CPU_COUNT}
    - make install
    - rm -f "$PREFIX"/lib/*.la
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - libtool
    - make
    - pkg-config

tests:
  - script:
      - filecap -d
      - netcap
      - pscap
  - package_contents:
      bin:
        - filecap
        - netcap
        - pscap
      include:
        - cap-ng.h
      lib:
        - cap-ng
        - drop_ambient
      files:
        - lib/pkgconfig/libcap-ng.pc
        - share/aclocal/cap-ng.m4
        - share/bash-completion/completions/cap-audit
        - share/bash-completion/completions/filecap
        - share/bash-completion/completions/libcap-ng.bash_completion
        - share/bash-completion/completions/netcap
        - share/bash-completion/completions/pscap
        - share/man/man3/*.3
        - share/man/man7/*.7
        - share/man/man8/*.8
      strict: true

about:
  summary: A library that makes using POSIX capabilities easier
  description: |
    Libcap-ng is a library that makes programming with POSIX capabilities easier.
    It also provides utilities for analyzing the capabilities of running processes
    and files, including `filecap`, `netcap`, and `pscap`.
  license: LGPL-2.1-or-later AND GPL-2.0-or-later
  license_file:
    - COPYING
    - COPYING.LIB
  homepage: https://people.redhat.com/sgrubb/libcap-ng/
  documentation: https://github.com/stevegrubb/libcap-ng/tree/master/docs
  repository: https://github.com/stevegrubb/libcap-ng

extra:
  recipe-maintainers:
    - salim-b
